module.exports = [
  {
    name: "Granola",
    description: "Delicious and healthy granola mix.",
    image: "https://i.imgur.com/9y3g7aL.jpg",
    price: 24.11,
    CategoryId: 1,
  },
  {
    name: "Cashew Nuts",
    description: "Crunchy and nutritious cashew nuts.",
    image: "https://i.imgur.com/PO6sCrG.jpg",
    price: 32.12,
    CategoryId: 1,
  },
  {
    name: "Almonds",
    description: "Raw and wholesome almonds.",
    image: "https://i.imgur.com/L5mV5n8.jpg",
    price: 28.58,
    CategoryId: 1,
  },
  {
    name: "Walnuts",
    description: "Rich in omega-3 walnuts.",
    image: "https://i.imgur.com/sEzxZIo.jpg",
    price: 17.18,
    CategoryId: 1,
  },
  {
    name: "Peanuts",
    description: "Tasty roasted peanuts.",
    image: "https://i.imgur.com/ynpTHTJ.jpg",
    price: 20.2,
    CategoryId: 1,
  },
  {
    name: "Corn Flakes",
    description: "Crispy corn flakes.",
    image: "https://i.imgur.com/DY8x7e5.jpg",
    price: 46.92,
    CategoryId: 1,
  },
  {
    name: "Oats",
    description: "Healthy whole oats.",
    image: "https://i.imgur.com/wnzDEGx.jpg",
    price: 37.95,
    CategoryId: 1,
  },
  {
    name: "Rye",
    description: "Nutritious rye grains.",
    image: "https://i.imgur.com/zM8iv6V.jpg",
    price: 33.8,
    CategoryId: 1,
  },
  {
    name: "Sesame Seeds",
    description: "Organic sesame seeds.",
    image: "https://i.imgur.com/nIT1Aeq.jpg",
    price: 12.72,
    CategoryId: 1,
  },
  {
    name: "Chia Seeds",
    description: "High-fiber chia seeds.",
    image: "https://i.imgur.com/hw8a2T0.jpg",
    price: 34.2,
    CategoryId: 1,
  },
  {
    name: "Quinoa",
    description: "Protein-rich organic quinoa.",
    image: "https://i.imgur.com/OMp7TjR.jpg",
    price: 27.21,
    CategoryId: 1,
  },
  {
    name: "Sunflower Seeds",
    description: "Sunflower seeds with vitamins.",
    image: "https://i.imgur.com/qHgk4GA.jpg",
    price: 22.72,
    CategoryId: 1,
  },
  {
    name: "Honey",
    description: "Pure and natural honey.",
    image: "https://i.imgur.com/OU8YYcS.jpg",
    price: 32.57,
    CategoryId: 1,
  },
  {
    name: "Cinnamon",
    description: "Aromatic ground cinnamon.",
    image: "https://i.imgur.com/nEf3zYk.jpg",
    price: 37.82,
    CategoryId: 1,
  },
  {
    name: "Vanilla",
    description: "Flavorful vanilla extract.",
    image: "https://i.imgur.com/XyCBefW.jpg",
    price: 22.43,
    CategoryId: 1,
  },
  {
    name: "Matcha",
    description: "High-quality matcha powder.",
    image: "https://i.imgur.com/TxH6JPe.jpg",
    price: 18.19,
    CategoryId: 1,
  },
  {
    name: "Spirulina",
    description: "Nutrient-dense spirulina powder.",
    image: "https://i.imgur.com/69As2ZL.jpg",
    price: 17.43,
    CategoryId: 1,
  },
  {
    name: "Sweetener",
    description: "Natural sweetener alternative.",
    image: "https://i.imgur.com/4QUJZtX.jpg",
    price: 43.97,
    CategoryId: 1,
  },
  {
    name: "Glucose",
    description: "Liquid glucose syrup.",
    image: "https://i.imgur.com/BdVYV3J.jpg",
    price: 10.53,
    CategoryId: 1,
  },
  {
    name: "Agave Syrup",
    description: "Organic agave syrup.",
    image: "https://i.imgur.com/4MyOTyB.jpg",
    price: 42.12,
    CategoryId: 1,
  },
  {
    name: "Peanut Butter",
    description: "Creamy peanut butter.",
    image: "https://i.imgur.com/tXYkL8Y.jpg",
    price: 25.51,
    CategoryId: 1,
  },
  {
    name: "Soy Milk",
    description: "Healthy soy milk.",
    image: "https://i.imgur.com/L9Ke24p.jpg",
    price: 10.01,
    CategoryId: 1,
  },
  {
    name: "Almond Milk",
    description: "Delicious almond milk.",
    image: "https://i.imgur.com/t3nK1cM.jpg",
    price: 32.87,
    CategoryId: 1,
  },
  {
    name: "Coconut Milk",
    description: "Creamy coconut milk.",
    image: "https://i.imgur.com/N8G7l5Z.jpg",
    price: 34.45,
    CategoryId: 1,
  },
  {
    name: "Yogurt",
    description: "Vegan yogurt variety.",
    image: "https://i.imgur.com/D1CWv5g.jpg",
    price: 16.56,
    CategoryId: 1,
  },
  {
    name: "Dulce de Leche",
    description: "Sweet dulce de leche.",
    image: "https://i.imgur.com/1eVCzHH.jpg",
    price: 21.08,
    CategoryId: 1,
  },
  {
    name: "Eggs",
    description: "Organic and fresh eggs.",
    image: "https://i.imgur.com/ZgBqZtG.jpg",
    price: 24.51,
    CategoryId: 1,
  },
  {
    name: "Vegan Pudding",
    description: "Delicious vegan pudding.",
    image: "https://i.imgur.com/zBtk2Xg.jpg",
    price: 11.27,
    CategoryId: 1,
  },
  {
    name: "Seitan Roast",
    description: "Satisfying seitan roast.",
    image: "https://i.imgur.com/qPjV8OT.jpg",
    price: 21.08,
    CategoryId: 1,
  },
  {
    name: "Vegan Cheese",
    description: "Creamy vegan cheese.",
    image: "https://i.imgur.com/ft19bX2.jpg",
    price: 21.38,
    CategoryId: 1,
  },
  {
    name: "Vegan Salami",
    description: "Tasty vegan salami.",
    image: "https://i.imgur.com/7u6UyCF.jpg",
    price: 37.64,
    CategoryId: 1,
  },
  {
    name: "Whole Grain Pasta",
    description: "Nutritious whole grain pasta.",
    image: "https://i.imgur.com/7fH5Ux3.jpg",
    price: 44.74,
    CategoryId: 1,
  },
  {
    name: "Rustic Potato Chips",
    description: "Crispy rustic potato chips.",
    image: "https://i.imgur.com/DZV0mIw.jpg",
    price: 5.98,
    CategoryId: 1,
  },
  {
    name: "Yerba Mate",
    description: "Traditional yerba mate.",
    image: "https://i.imgur.com/GW77gOh.jpg",
    price: 21.54,
    CategoryId: 1,
  },
  {
    name: "Tea",
    description: "Refreshing tea leaves.",
    image: "https://i.imgur.com/8oR4qEN.jpg",
    price: 20.01,
    CategoryId: 1,
  },
  {
    name: "Coffee",
    description: "Rich and aromatic coffee.",
    image: "https://i.imgur.com/LBdGZbY.jpg",
    price: 44.1,
    CategoryId: 1,
  },
];
